/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Supra.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function Supra(props) {
  const { nodes, materials } = useGLTF('models/Supra.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry}>
        <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.Object_10.geometry} material={materials.Black2Mtl} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Lights2Mtl} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Lights1Mtl} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Calipers1Mtl} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.RimC1Mtl} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Lights4Mtl} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Lights5Mtl} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Lights7Mtl} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Noir2Mtl} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Rotor1Mtl} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.Black1Mtl} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Glass1Mtl} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.Noir3Mtl} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Noir1Mtl} />
      <mesh geometry={nodes.Object_6001.geometry} material={materials.BaseMtl} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.RGlass1Mtl} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Windows1Mtl} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Black2Mtl} />
    </group>
  )
}

useGLTF.preload('/Supra.glb')
