/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Supra.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from "valtio"
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';

export function Supra(props) {
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)
  const { nodes, materials } = useGLTF('/models/Supra.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry} material={materials.BaseMtl} material-color={snap1.base.BaseMtl} visible={overlay === 1}/>
      <mesh geometry={nodes.Body001.geometry} material={materials.Slaughter} material-color={snap1.base.BaseMtl} visible={overlay === 2}/>
      <mesh geometry={nodes.Body002.geometry} material={materials.BatLady} material-color={snap1.base.BaseMtl} visible={overlay === 3}/>
      <mesh geometry={nodes.Body003.geometry} material={materials.BrakeLine} material-color={snap1.base.BaseMtl} visible={overlay === 4}/>
      <mesh geometry={nodes.Body004.geometry} material={materials.Danger} material-color={snap1.base.BaseMtl} visible={overlay === 5}/>
      <mesh geometry={nodes.Body005.geometry} material={materials.Embers} material-color={snap1.base.BaseMtl} visible={overlay === 6}/>
      <mesh geometry={nodes.Body006.geometry} material={materials.SpiderID} material-color={snap1.base.BaseMtl} visible={overlay === 7}/>
      <mesh geometry={nodes.Body007.geometry} material={materials.Fluid} material-color={snap1.base.BaseMtl} visible={overlay === 8}/>
      <mesh geometry={nodes.Body008.geometry} material={materials.HotRods} material-color={snap1.base.BaseMtl} visible={overlay === 9}/>
      <mesh geometry={nodes.Body009.geometry} material={materials.Mayan} material-color={snap1.base.BaseMtl} visible={overlay === 10}/>
      <mesh geometry={nodes.Body010.geometry} material={materials.SeaBreeze} material-color={snap1.base.BaseMtl} visible={overlay === 11}/>
      <mesh geometry={nodes.Body011.geometry} material={materials.ShapeShifter} material-color={snap1.base.BaseMtl} visible={overlay === 12}/>
      <mesh geometry={nodes.Body012.geometry} material={materials.Silk} material-color={snap1.base.BaseMtl} visible={overlay === 13}/>
      <mesh geometry={nodes.Body013.geometry} material={materials.SnakeSkin} material-color={snap1.base.BaseMtl} visible={overlay === 14}/>
      <mesh geometry={nodes.Body014.geometry} material={materials.Flare} material-color={snap1.base.BaseMtl} visible={overlay === 15}/>
      <mesh geometry={nodes.Body015.geometry} material={materials.Dominator} material-color={snap1.base.BaseMtl} visible={overlay === 16}/>
      <mesh geometry={nodes.Body016.geometry} material={materials.TopGun} material-color={snap1.base.BaseMtl} visible={overlay === 17}/>
      <mesh geometry={nodes.Body017.geometry} material={materials.Explosion} material-color={snap1.base.BaseMtl} visible={overlay === 18}/>
      <mesh geometry={nodes.Body018.geometry} material={materials.WildWest} material-color={snap1.base.BaseMtl} visible={overlay === 19}/>
      <mesh geometry={nodes.Body019.geometry} material={materials.Zombie} material-color={snap1.base.BaseMtl} visible={overlay === 20}/>
      <mesh geometry={nodes.Object_10.geometry} material={materials.Black2Mtl} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Lights2Mtl} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Lights1Mtl} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Calipers1Mtl} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.RimC1Mtl} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Lights4Mtl} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Lights5Mtl} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Lights7Mtl} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Noir2Mtl} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Rotor1Mtl} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.Black1Mtl} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Glass1Mtl} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.Noir3Mtl} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Noir1Mtl} />
      <mesh geometry={nodes.Object_6001.geometry} material={materials.BaseMtl} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.RGlass1Mtl} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Windows1Mtl} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Black2Mtl} />
    </group>
  )
}

useGLTF.preload('/models/Supra.glb')
